### ISSUE TITLE
permission denied for schema public

### ISSUE THREAD

**Issue by akshaynstack** [zainulabedeen123/best-saas-kit#3]
I got this error right after cloning your repo and sign up and after verification

![image](https://github.com/user-attachments/assets/6c713c60-81ef-4361-a52a-73d66013b6b9)

**Comment by zainulabedeen123** [comment]
Run Supabase/Migration Queryies in SQL Editor on Supabase Dashboard

**Comment by akshaynstack** [comment]
Yeah I did that

**Comment by akshaynstack** [comment]
This is fixed. I am closing it. Thank you
